[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    login_guest: marker for tests with login link
    login_user: marker for tests with registered user
    need_review: marker for tests that need review
